# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_OPLUS_SM4350R_CHARGER)	+= oplus/
obj-$(CONFIG_OPLUS_POWER_UTIL)  += oplus_util/
